### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#127]
- [x] Study HingeLowRank more carefully
  - [x] Refactor like bvls.
  - [x] Add debug tools like bvls.
  - [x] Simulate inputs as if
