### ISSUE TITLE
TODO v1.1.50

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#135]
- [x] Test `mean` and `var` function.
- [x] Amend `ad.matrix.standardize` accordingly.
- [x] Implement `css_cov` for sequential testing. Maybe `method="fixed"` vs `method="sequential"` and `solver="greedy"` vs `solver="swapping"`?
- [x] ConvexGatedRelu
