### ISSUE TITLE
2023-10-01 TODO

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#16]
- [x] pyproject.toml
  - [x] Follow classifiers as in numpy
  - [x] Remove pybind, cppimport from deps and poetry deps
- [x] README.md better descriptions
- [x] tests
  - [x] test_grpnet fill in
- [x] docs
  - [x] dev
    - [x] Versioning simplify and better format
    - [x] Write command for git tag 
- [x] adelie
  - [x] bcd.py
    - [x] use h stars in docs
    - [x] say undefined behavior when conditions are not satisfied (maybe throw exception?)
    - [x] more descriptive return name
    - [x] solve description not exactly correct? Well-defined iff ||v|| <= l1 or  ||v_S|| <= l1.
    - [x] Root should only take quad, linear, l1 because it solves root_function. Well-defined iff ||v|| >= l1 and ||v_S|| < l1.
  - [x] matrix.py
    - [x] rethink API. Really should only expose bare minimum, highest-level routine. Right now, we are enforcing a dense representation of block and col. As a result, we must enforce column major for dense.
  - [x]  state.py
    - [x] move X_k description to solve_pin
    - [x] Alpha bound [0,1]
    - [x] Penalty >= 0
    - [x] Strong_set is a subset of groups
    - [x] Strong_begin say how much you should read also.
    - [x] strong_A_diag change name globally to strong_var and math k instead.
    - [x] default vals for some configs
    - [x] globally change thr to tol
    - [x] rsq_slope_tol, rsq_curv_tol
    - [x] strong_grad math k
    - [x] Make readonly!
  - [x] grpnet 
    - [x] give same bound information for wach param
