### ISSUE TITLE
TODO 2023-10-06

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#20]
- [x] Export covariance state to Python
- [x] Test covariance state
- [x] Document covariance state
- [x] Implement `solve_pin_cov`
- [x] Test `solve_pin_cov`
- [x] Change states to all own objects
- [x] Redocument in export file and simplify `state.py`
- [x] Change matrices to be split into `pin_naive_base` `pin_naive_dense` etc.
- [x] Cov lazy
- [x] Change file names (final)
- [x] Basil idea:
  - [x] center `y` if fitting with intercept (save the mean also to output intercept value)
  - [x] Strong set only includes the un-l1-penalized variables at first. Use lambda_max to fit always! Since fitting part assumes zero coefficient outside strong set, it must be lambda_max by definition to be well-defined. Use `X.to_dense()` to grab the respective blocks. Process them to get strong_vars and UD, V (centering first if necessary). 
  - [x] Now that initial solution has been found and some variables are updated, the current state should be in its invariance state.
  - [x] `X.init_states(...)` can do a one-pass through the entire matrix to compute a lot of quantities like gradient, `||X_k||_2^2`, and `X_k mean`. This will give us all the initial states related to `X`. 
  - [x] Strong/EDPP rule to omit variables.
  - [x] `X.to_dense(j, q, out)` stores the dense version of the column blocks into out. From this, we can compute (possibly centered if fitting with intercept) SVD of the block and save the necessary UD and V separately. This will only be done on the strong set.
- [x] Implement `MatrixPinNaiveSubset` which views a subset of a matrix on the strong set and integrate into `solve_basil_naive.hpp`.
- [x] Figure out interface for  `MatrixBasilNaiveBase`. Export bindings and add to `matrix.py`.
- [x] Implement `MatrixBasilNaiveDense`, export, add to `matrix.py`, test.
- [x] Export `StateBasilNaive` with `MatrixBasilNaiveBase`. 
- [x] Extend `state.py` to include `basil_base`, `basil_naive_base`, `basil_naive`, etc. Create tests.
- [x] Export `solve_basil_naive`. Add to `solver.py`. Test.
