### ISSUE TITLE
TODO 11/8

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#30]
- [x] `n_threads_n`, `n_threads_p` to control different parts of the algorithm.
- [x] Remove the capping of `n_threads` because there's significant cost to changing pool size. Just keep it fixed.
- [x] Recommendation: all `n_threads_` should be either `1` or the same value, including the one used in matrix classes.
- [x] Benchmark OMP to be absolutely sure that there is huge cost to changing thread pool size.
- [x] `abs_grad` needs to change to include elastic net correction `lmda * (1-alpha) * w_g * beta_g`!!!!! Double check we only need to change the definition for `abs_grad`.
- [x] fix sparse matrix export of beta so that it is faster!
- [x] Implement matrix class for phased ancestry
- [x] Write tutorial notebook for using different SNP styles.
- [x] Write a script to subset data (calldata/ancestry/phenotype) and scp the results to local machine.
- [x] Write exact script for processing all existing data files to `.snpdat` format.
- [x] Try using adelie on real data!
- [x] Change SNP matrices to include a dense component
