### ISSUE TITLE
TODO 12/02

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#31]
- [x] New repo `snpper`
  - [x] Move `snputils` related things here
  - [x] Package it with C++ backend.
- [x] `gen_to_snpdat`
  - [x] Add `samples_indices` and `snps_indices` option. Useful for debugging, splitting to training and testing, and removing SNPs based on MAF. `None` means use all.
  - [x] Write custom converter from `calldatas` -> `calldata` (I x 2 * snp) (F storage, int8_t). Also applies for `lai`. 
  - [x] Save converted calldata and LAI using `np.save` instead of `np.savetxt`.
  - [x] Implement `calldata_path` and `lai_path` which supplies path of converted calldata and LAI `.npy` files.
