### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#56]
- [x] `null_intercept`: every model should have this which is the null model with only intercept. We should save this value. It's useful when we need to compute deviance under the null model. Sometimes the model may have other unpenalized terms, so we cannot just take the first deviance from the output.
- [x] Implement CV
- [x] Refactor tests to be shorter and cleaner
- [x] ~~remove automatic scaling of weights. It's super annoying in CV implementation. Let the user be responsible for scaling.~~ can't do this because the correctness of the solver depends on the weights summing to 1
- [x] `multiglm` and `glm`. Store a boolean flag indicating multi-response for `multiglm`.
- [x] `multiglm`, `multigaussian` inherit from single case with single case state variables initialized as if we transformed the problem to a single problem. Abstract out all the parts of the code that interface differently due to multi vs single. E.g.
  - [x] `multiglm` any time we interact with GLM objects, the interface is different so we must swap out those pieces of code.
  - [x] ~~`multiglm` must also add a correction routine for symmetric glms.~~ this doesn't seem needed and was only needed in glmnet because they optimize each class at a time.
  - [x] `multigaussian` and `multiglm` need to do some housekeeping after the sub-solver is done. E.g. modify the betas and intercepts output. 
- [x] Remove `default_init` and push all the initialization into the class defined inside the maker functions.
- [x] Write checks that guard against bad inputs.
