### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/adelie#95]
- [ ] `MatrixNaiveXSubset` should save `subset` as a map. It is inconsistent with how other matrices are defined.
- [ ] Make sure all "user inputs" are saved as a map. Any derived quantities can be saved internally without a map to maximize shared code between Python and R. 
- [ ] All "user inputs" should have a reference of a *copy* saved in the Python side.

**Comment by JamesYang007** [comment]
#94
